### ISSUE TITLE
no reset at 0:00

### ISSUE THREAD

**Issue by yasars** [jeroenterheerdt/HADailySensor#12]
hi i install your plugin!! all working fine but at 0:00 no reset of the data ...

i have  tried to create an automation but i have this error: (Message malformed: Service daily.stromverbrauch pro tag_reset does not match format <domain>.<name> for dictionary value @ data['action'][0]['service'])

any idea...?

**Comment by yasars** [comment]
Which config? And where.can i find it? 

I have an esp that measures the current (the current one) at the current automat by means of a light barrier.
![IMG_20210608_200759](https://user-images.githubusercontent.com/41986136/121235726-74c9da00-c895-11eb-8684-566628146f61.jpg)
![Screenshot_2021-06-08-20-08-26-141_com android chrome](https://user-images.githubusercontent.com/41986136/121235745-77c4ca80-c895-11eb-8af4-1a40252fe1a9.jpg)

**Comment by jeroenterheerdt** [comment]
so what is the configuration you put in the sensor?

**Comment by yasars** [comment]
First and second picture

**Comment by jeroenterheerdt** [comment]
looking at the first picture it looks like the reset did happen, right? It drops to 0 at 00:00 and then builds up again. Also, I see the component is calling `daily.stromverbrauch pro tag_reset`. Can you see if there is indeed a service that looks like: `daily.[something]_reset` on your system?

**Comment by yasars** [comment]
I have look herr in automation ... I found it , but can make an automation ...
![Uploading IMG_20210609_191509.jpg…]()

**Comment by jeroenterheerdt** [comment]
not sure what you mean. sum is the right option if you want to total the amount over a day. The error message you had is because you have spaces in your sensor name: `daily.test day/kw stdev_reset` is never going to work as a service name as spaces are not allowed. I would advice against using spaces in your entity names, that way you don't run into any issues with components such as this one. rename you `stromverbrauch pro tag` to `stromverbrach_pro_tag` and re-add the daily sensor. everything should work fine then. The spaces are the issue.
