### ISSUE TITLE
HADaily Sensor not reset at 12AM

### ISSUE THREAD

**Issue by kaizersoje** [jeroenterheerdt/HADailySensor#17]
I upgraded to v0.3.5 yesterday and have noticed that the HADaily Sensor did not get reset at 12AM. Could you look into this?

I have attached a screenshot of the daily sensor for the last 4 days. The yellow highlights show that the sensor starts with 0 at 12AM. However, it did not get reset on 12 Aug as shown by the pink highlight and continued where it left off from yesterday.

![image](https://user-images.githubusercontent.com/54566217/129129652-8dc35062-efd4-429b-951f-14c781c4c73f.png)

**Comment by jeroenterheerdt** [comment]
Can you revert back to the previous version to see if that solves the issue?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: kaizersoje ***@***.***>
Sent: Wednesday, August 11, 2021 7:36:30 PM
To: jeroenterheerdt/HADailySensor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeroenterheerdt/HADailySensor] HADaily Sensor not reset at 12AM (#17)


I upgraded to v0.3.5 yesterday and have noticed that the HADaily Sensor did not get reset at 12AM. Could you look into this?

I have attached a screenshot of the daily sensor for the last 4 days. The yellow highlights show that the sensor starts with 0 at 12AM. However, it did not get reset on 12 Aug as shown by the pink highlight and continued where it left off from yesterday.

[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F54566217%2F129129652-8dc35062-efd4-429b-951f-14c781c4c73f.png&data=04%7C01%7C%7C403e588413c247529e2708d95d39fddd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643325922386041%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZZtwUIqHbnk6OoJ5LNhvls%2BWLNvn55V1uSyDxGL5LiI%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeroenterheerdt%2FHADailySensor%2Fissues%2F17&data=04%7C01%7C%7C403e588413c247529e2708d95d39fddd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643325922386041%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pu4iQxz04zbj2bTuV3XJyJi%2BvSPROt4fNeZxhJBgc2g%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB6PIPQX7UCPS772GL5QS73T4MXS5ANCNFSM5CAAA4MQ&data=04%7C01%7C%7C403e588413c247529e2708d95d39fddd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643325922396032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M9rymm1reqOJapis9Sj7sumFpMKIXL6%2BEAGWBUCpHY0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C403e588413c247529e2708d95d39fddd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643325922396032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AFlrSsYz3Rr7fPDPT83CmSVymlmHn7qRJGw4q%2FwNFaM%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C403e588413c247529e2708d95d39fddd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643325922406021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qa1zSCPax0eiT3DvmleCfMsUAp6Uh%2B2hF6AT15vrNWQ%3D&reserved=0>.

**Comment by kaizersoje** [comment]
Yes, I am going to do that but can confirm if it solves the issue tomorrow.

**Comment by jeroenterheerdt** [comment]
thanks, do let me know please. my sensors reset over time, so I am not able to reproduce this. Also look at error logs and provide anything that sounds relevant

**Comment by kaizersoje** [comment]
V0.3.4 worked and reset the sensor at 12AM. It looks like the in v0.3.5 it may not be getting reset at 12AM.

**Comment by jeroenterheerdt** [comment]
well, it does reset on  my end, I am seeing this: 
![image](https://user-images.githubusercontent.com/8188990/129281756-8883eae7-01ef-4b92-85e7-6e6841e17dc8.png)

**Comment by kaizersoje** [comment]
Do you reckon it is not doing so due to a different timezone?

**Comment by jeroenterheerdt** [comment]
maybe, I'll check.

**Comment by jeroenterheerdt** [comment]
I just tried it on my dev box and it resets fine. I am not sure what is going on here. Can you try creating a new sensor just to see if that does reset?

**Comment by jeroenterheerdt** [comment]
please install https://github.com/jeroenterheerdt/HADailySensor/releases/tag/0.3.6-beta and see if you have any logs (you will need to have information logging enabled for this component)

**Comment by kaizersoje** [comment]
Just a question - If the daily sensor was created prior to v0.3.5, will it still get reset at midnight? I am asking since v0.3.5, the user can choose to select the auto_reset parameter when creating a new daily sensor.

**Comment by jeroenterheerdt** [comment]
By default auto_reset should be on, so yes.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jeroenterheerdt** [comment]
I started seeing this now as well, not sure why not before. I reverted the change in https://github.com/jeroenterheerdt/HADailySensor/releases/tag/v0.3.7

**Comment by jeroenterheerdt** [comment]
please install this beta to verify it works this time: https://github.com/jeroenterheerdt/HADailySensor/releases/tag/v0.3.8-beta

**Comment by kaizersoje** [comment]
Thx looks all good now.
